### ISSUE TITLE
Output of command line programs is only displayed on exit

### ISSUE THREAD

**Issue by spotlightishere** [CircuitCodes/push#1]
Certain programs relying on various control codes fail to render entirely under PUSH. Verified programs failing:
 - `nano`
 - `vim`
 - `htop`

**Comment by CircuitCodes** [comment]
That is confirmed, `nano` does not work on WSL or plain old Linux either.

**Comment by CircuitCodes** [comment]
I do have a fix to the (n)curses issue, which will be pushed tomorrow morning.

The output is only displayed on exit, which causes an issue on more than curses-based programs. The fleipold/jproc dependency will be removed as a result.

**Comment by CircuitCodes** [comment]
As this shell has no semblance of environmental variables or a TTY, the fix for this has been postponed.
